version: "3.0"

services:
  todo-db:
    image: postgres:11.5 # specify image to build container from
    command: -p 5433
    ports:
      - "5433:5433" # specify port forwarding
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sample_todo
